# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calmbot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calmbot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcalmbot.proto\x12\x07\x63\x61lmbot\"/\n\x0eLogMoodRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04mood\x18\x02 \x01(\t\" \n\x0fLogMoodResponse\x12\r\n\x05reply\x18\x01 \x01(\t\"/\n\x0b\x43hatRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1d\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t\">\n\x0eJournalRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04mood\x18\x02 \x01(\t\x12\r\n\x05\x65ntry\x18\x03 \x01(\t\" \n\x0fJournalResponse\x12\r\n\x05reply\x18\x01 \x01(\t\"\"\n\x0fProgressRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"E\n\x10ProgressResponse\x12\x10\n\x08\x65motions\x18\x01 \x03(\t\x12\x0e\n\x06\x63ounts\x18\x02 \x03(\x05\x12\x0f\n\x07summary\x18\x03 \x01(\t2\x89\x02\n\x0e\x43\x61lmbotService\x12<\n\x07LogMood\x12\x17.calmbot.LogMoodRequest\x1a\x18.calmbot.LogMoodResponse\x12\x33\n\x04\x43hat\x12\x14.calmbot.ChatRequest\x1a\x15.calmbot.ChatResponse\x12@\n\x0bSaveJournal\x12\x17.calmbot.JournalRequest\x1a\x18.calmbot.JournalResponse\x12\x42\n\x0bGetProgress\x12\x18.calmbot.ProgressRequest\x1a\x19.calmbot.ProgressResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calmbot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGMOODREQUEST']._serialized_start=26
  _globals['_LOGMOODREQUEST']._serialized_end=73
  _globals['_LOGMOODRESPONSE']._serialized_start=75
  _globals['_LOGMOODRESPONSE']._serialized_end=107
  _globals['_CHATREQUEST']._serialized_start=109
  _globals['_CHATREQUEST']._serialized_end=156
  _globals['_CHATRESPONSE']._serialized_start=158
  _globals['_CHATRESPONSE']._serialized_end=187
  _globals['_JOURNALREQUEST']._serialized_start=189
  _globals['_JOURNALREQUEST']._serialized_end=251
  _globals['_JOURNALRESPONSE']._serialized_start=253
  _globals['_JOURNALRESPONSE']._serialized_end=285
  _globals['_PROGRESSREQUEST']._serialized_start=287
  _globals['_PROGRESSREQUEST']._serialized_end=321
  _globals['_PROGRESSRESPONSE']._serialized_start=323
  _globals['_PROGRESSRESPONSE']._serialized_end=392
  _globals['_CALMBOTSERVICE']._serialized_start=395
  _globals['_CALMBOTSERVICE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
