# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import calmbot_pb2 as calmbot__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in calmbot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalmbotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogMood = channel.unary_unary(
                '/calmbot.CalmbotService/LogMood',
                request_serializer=calmbot__pb2.LogMoodRequest.SerializeToString,
                response_deserializer=calmbot__pb2.LogMoodResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/calmbot.CalmbotService/Chat',
                request_serializer=calmbot__pb2.ChatRequest.SerializeToString,
                response_deserializer=calmbot__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.SaveJournal = channel.unary_unary(
                '/calmbot.CalmbotService/SaveJournal',
                request_serializer=calmbot__pb2.JournalRequest.SerializeToString,
                response_deserializer=calmbot__pb2.JournalResponse.FromString,
                _registered_method=True)
        self.GetProgress = channel.unary_unary(
                '/calmbot.CalmbotService/GetProgress',
                request_serializer=calmbot__pb2.ProgressRequest.SerializeToString,
                response_deserializer=calmbot__pb2.ProgressResponse.FromString,
                _registered_method=True)


class CalmbotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LogMood(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveJournal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalmbotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogMood': grpc.unary_unary_rpc_method_handler(
                    servicer.LogMood,
                    request_deserializer=calmbot__pb2.LogMoodRequest.FromString,
                    response_serializer=calmbot__pb2.LogMoodResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=calmbot__pb2.ChatRequest.FromString,
                    response_serializer=calmbot__pb2.ChatResponse.SerializeToString,
            ),
            'SaveJournal': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveJournal,
                    request_deserializer=calmbot__pb2.JournalRequest.FromString,
                    response_serializer=calmbot__pb2.JournalResponse.SerializeToString,
            ),
            'GetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgress,
                    request_deserializer=calmbot__pb2.ProgressRequest.FromString,
                    response_serializer=calmbot__pb2.ProgressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calmbot.CalmbotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calmbot.CalmbotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CalmbotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LogMood(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calmbot.CalmbotService/LogMood',
            calmbot__pb2.LogMoodRequest.SerializeToString,
            calmbot__pb2.LogMoodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calmbot.CalmbotService/Chat',
            calmbot__pb2.ChatRequest.SerializeToString,
            calmbot__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveJournal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calmbot.CalmbotService/SaveJournal',
            calmbot__pb2.JournalRequest.SerializeToString,
            calmbot__pb2.JournalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calmbot.CalmbotService/GetProgress',
            calmbot__pb2.ProgressRequest.SerializeToString,
            calmbot__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
